<a href="https://colab.research.google.com/github/melkanzi/PhD/blob/main/Preprocessing/CASAS_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data Preprocessing Pipeline for CASAS Dataset

### 1. Mount Google Drive

First, we need to mount Google Drive to access the dataset. This will prompt you to authenticate your Google account.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### 2. Load the Dataset

Next, we'll load the `CASAS` dataset. Please ensure the path below points to your dataset file in Google Drive. I am assuming it's a CSV file. If it's a different format, please adjust the loading function accordingly.

In [ ]:
import pandas as pd
import os

# Adjust this path to your actual dataset *folder* location in Google Drive
casas_folder_path = '/content/drive/MyDrive/Datasets/CASAS' # Example folder path, modify if needed
all_files = []
df_list = []

try:
    # List all files in the specified folder and its subfolders
    for root, _, files in os.walk(casas_folder_path):
        for file in files:
            if file.endswith('.csv'):
                all_files.append(os.path.join(root, file))

    if not all_files:
        print(f"Error: No CSV files found in the folder {casas_folder_path}.")
        df = None
    else:
        print(f"Found {len(all_files)} CSV files in {casas_folder_path}.")
        for file_path in all_files:
            try:
                # Read each CSV file
                current_df = pd.read_csv(file_path)
                df_list.append(current_df)
                print(f"Loaded {file_path}")
            except Exception as e:
                print(f"Error reading {file_path}: {e}")

        if df_list:
            # Concatenate all DataFrames into one
            df = pd.concat(df_list, ignore_index=True)
            print("\nAll CSV files concatenated successfully.")
            print("First 5 rows of the combined dataset:")
            display(df.head())
            print("\nCombined Dataset Info:")
            df.info()
        else:
            print("No DataFrames were successfully loaded. DataFrame will be None.")
            df = None

except FileNotFoundError:
    print(f"Error: Folder not found at {casas_folder_path}. Please check the path.")
    df = None
except Exception as e:
    print(f"An unexpected error occurred: {e}")
    df = None

Found 100 CSV files in /content/drive/MyDrive/Datasets/CASAS.
Loaded /content/drive/MyDrive/Datasets/CASAS/p20.t2.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p17.t3.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p21.t2.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p20.t4.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p20.t3.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p18.t4.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p20.t5.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p18.t5.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p17.t1.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p21.t1.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p17.t5.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p17.t2.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p17.t4.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p18.t3.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p18.t1.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p20.t1.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p18.t2.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p53.t5.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p29.t2.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p52.t4.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p29.t4.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p54.t5.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p23.t4.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p26.t5.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p58.t5.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p53.t4.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p27.t3.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p57.t2.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p52.t1.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p23.t5.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p21.t3.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p52.t5.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p31.t2.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p52.t3.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p31.t5.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p27.t5.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p54.t1.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p31.t4.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p57.t1.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p58.t1.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p59.t3.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p24.t3.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p57.t3.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p30.t2.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p59.t5.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p55.t5.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p53.t2.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p56.t4.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p56.t5.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p23.t2.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p27.t2.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p31.t1.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p29.t3.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p58.t3.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p58.t4.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p58.t2.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p30.t1.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p53.t1.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p24.t5.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p21.t5.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p52.t2.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p24.t2.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p30.t4.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p21.t4.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p26.t4.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p24.t1.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p22.t2.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p22.t3.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p54.t4.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p55.t3.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p26.t1.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p59.t4.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p27.t1.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p59.t2.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p30.t5.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p56.t3.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p56.t2.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p56.t1.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p27.t4.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p53.t3.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p55.t1.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p29.t1.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p26.t3.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p30.t3.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p54.t2.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p29.t5.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p22.t4.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p54.t3.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p55.t4.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p22.t1.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p55.t2.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p57.t4.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p23.t1.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p57.t5.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p31.t3.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p59.t1.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p23.t3.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p26.t2.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p24.t4.csv
Loaded /content/drive/MyDrive/Datasets/CASAS/p22.t5.csv

All CSV files concatenated successfully.
First 5 rows of the combined dataset:

         date             time sensor message
0  2008-04-04  12:35:02.226475    M14      ON
1  2008-04-04  12:35:04.249915    M15      ON
2  2008-04-04  12:35:04.689817    M16      ON
3  2008-04-04  12:35:05.630524    M13     OFF
4  2008-04-04   12:35:05.78357    M17      ON

Combined Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5161 entries, 0 to 5160
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     5161 non-null   object
 1   time     5161 non-null   object
 2   sensor   5161 non-null   object
 3   message  5161 non-null   object
dtypes: object(4)
memory usage: 161.4+ KB

### 3. Handle Missing Values by Removal

This step removes any rows that contain missing values (NaN, None, etc.).

In [ ]:
if df is not None:
    initial_rows = df.shape[0]
    df.dropna(inplace=True)
    rows_after_missing_values = df.shape[0]
    print(f"Rows before dropping missing values: {initial_rows}")
    print(f"Rows after dropping missing values: {rows_after_missing_values}")
    print(f"Number of rows removed: {initial_rows - rows_after_missing_values}")
else:
    print("DataFrame is not loaded. Skipping missing value handling.")

Rows before dropping missing values: 5161
Rows after dropping missing values: 5161
Number of rows removed: 0

### 4. Remove Duplicates

This step identifies and removes any duplicate rows from the dataset.

In [ ]:
if df is not None:
    initial_rows = df.shape[0]
    df.drop_duplicates(inplace=True)
    rows_after_duplicates = df.shape[0]
    print(f"Rows before dropping duplicates: {initial_rows}")
    print(f"Rows after dropping duplicates: {rows_after_duplicates}")
    print(f"Number of duplicate rows removed: {initial_rows - rows_after_duplicates}")
else:
    print("DataFrame is not loaded. Skipping duplicate removal.")

Rows before dropping duplicates: 5161
Rows after dropping duplicates: 5161
Number of duplicate rows removed: 0

### 5. Fix Inconsistent Formats (Example: Strip Whitespace, Convert Data Types)

This step addresses inconsistent data formats. Without specific knowledge of your dataset's inconsistencies, a common practice is to strip whitespace from string columns and ensure columns are of their appropriate data types (e.g., converting 'object' types that should be numeric or datetime).

**Note:** You might need to customize this cell based on the actual inconsistencies in your 'CASAS' dataset. For example, if you have a `timestamp` column, ensure it's converted to a datetime object, or if there are specific string patterns to clean, add that logic here.

In [ ]:
if df is not None:
    # Example: Strip whitespace from all string columns
    for col in df.select_dtypes(include=['object']).columns:
        df[col] = df[col].astype(str).str.strip()
        print(f"Stripped whitespace from column: {col}")

    # Example: Convert a 'timestamp' or 'date' column to datetime objects
    # Replace 'your_timestamp_column' with the actual name of your timestamp column
    if 'timestamp' in df.columns:
        df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')
        print("Converted 'timestamp' column to datetime.")
    elif 'date' in df.columns:
        df['date'] = pd.to_datetime(df['date'], errors='coerce')
        print("Converted 'date' column to datetime.")
    else:
        print("No 'timestamp' or 'date' column found for automatic conversion.")
        print("Please manually convert relevant columns if they are not in the correct format.")

    print("\nDataFrame info after format fixing:")
    df.info()
else:
    print("DataFrame is not loaded. Skipping format fixing.")

Stripped whitespace from column: date
Stripped whitespace from column: time
Stripped whitespace from column: sensor
Stripped whitespace from column: message
Converted 'date' column to datetime.

DataFrame info after format fixing:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5161 entries, 0 to 5160
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     5161 non-null   datetime64[ns]
 1   time     5161 non-null   object
 2   sensor   5161 non-null   object
 3   message  5161 non-null   object
dtypes: datetime64[ns](1), object(3)
memory usage: 161.4+ KB

### 6. Convert Text Labels into Numeric Form Using One-Hot Encoding

This step identifies categorical columns (typically `object` or `category` dtypes) and converts them into a numerical format using one-hot encoding. This creates new binary columns for each unique category.

In [ ]:
if df is not None:
    # Identify categorical columns for one-hot encoding
    categorical_cols = df.select_dtypes(include=['object']).columns

    if len(categorical_cols) > 0:
        print(f"Categorical columns to be one-hot encoded: {list(categorical_cols)}")
        df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
        print("One-hot encoding applied.")
        print("First 5 rows after one-hot encoding:")
        display(df.head())
    else:
        print("No object (categorical) columns found for one-hot encoding.")
else:
    print("DataFrame is not loaded. Skipping one-hot encoding.")

Categorical columns to be one-hot encoded: ['time', 'sensor', 'message']
One-hot encoding applied.
First 5 rows after one-hot encoding:

,date,time_09:03:28.617601,time_09:03:29.105569,time_09:03:29.967462,time_09:03:30.84641,time_09:03:31.676519,time_09:03:31.974608,time_09:03:32.2486,time_09:03:33.483746,time_09:03:34.977824,...,message_3.34286,message_ABSENT,message_CLOSE,message_END,message_OFF,message_ON,message_OPEN,message_PRESENT,message_START,message_STOP_INSTRUCT
0,2008-04-04,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1,2008-04-04,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
2,2008-04-04,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
3,2008-04-04,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
4,2008-04-04,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False

### 7. Apply Normalization (Min-Max)

This step applies Min-Max Normalization to all numerical features. Min-Max scaling transforms features to a given range, typically between 0 and 1. This is important for many machine learning algorithms.

In [ ]:
from sklearn.preprocessing import MinMaxScaler

if df is not None:
    # Identify numerical columns for normalization (excluding any datetime columns that might remain)
    # We'll also exclude the timestamp column if it was just used for sorting and not a feature itself
    numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

    # Exclude any 'timestamp' or 'date' columns if they are still present and should not be scaled
    if 'timestamp' in numeric_cols:
        numeric_cols = numeric_cols.drop('timestamp')
    if 'date' in numeric_cols:
        numeric_cols = numeric_cols.drop('date')

    if len(numeric_cols) > 0:
        print(f"Numerical columns to be Min-Max normalized: {list(numeric_cols)}")
        scaler = MinMaxScaler()
        df[numeric_cols] = scaler.fit_transform(df[numeric_cols])
        print("Min-Max Normalization applied.")
        print("First 5 rows after normalization (numerical columns):")
        display(df.head())
    else:
        print("No numerical columns found for Min-Max Normalization (excluding datetime).")
else:
    print("DataFrame is not loaded. Skipping normalization.")

No numerical columns found for Min-Max Normalization (excluding datetime).

### 8. Split the Data Chronologically (70%-30% Split)

This step splits the data into training and testing sets based on chronological order. This is crucial for time-series data or any data where the temporal aspect is important.

**Important:** This step assumes you have a time-based column (e.g., 'timestamp', 'date') that has been converted to a datetime object. If not, please ensure such a column exists and is correctly typed before running this cell.

In [ ]:
if df is not None:
    # Ensure the DataFrame is sorted by the time-based column
    # Replace 'your_time_column' with the actual name of your time column (e.g., 'timestamp' or 'date')
    time_column = None
    if 'timestamp' in df.columns:
        time_column = 'timestamp'
    elif 'date' in df.columns:
        time_column = 'date'

    if time_column and pd.api.types.is_datetime64_any_dtype(df[time_column]):
        df.sort_values(by=time_column, inplace=True)
        print(f"DataFrame sorted by '{time_column}'.")

        # Determine the split point (70% for training)
        split_point = int(len(df) * 0.7)

        df_train = df.iloc[:split_point]
        df_test = df.iloc[split_point:]

        print(f"Data split chronologically into training (70%) and testing (30%).")
        print(f"Training set shape: {df_train.shape}")
        print(f"Testing set shape: {df_test.shape}")

        print("\nFirst 5 rows of Training Data:")
        display(df_train.head())
        print("\nFirst 5 rows of Test Data:")
        display(df_test.head())
    else:
        print("Error: No suitable time-based column ('timestamp' or 'date') found or it's not in datetime format for chronological split.")
        print("Please ensure your time column is correctly named and converted to datetime objects in the previous 'Fix Inconsistent Formats' step.")
else:
    print("DataFrame is not loaded. Skipping chronological split.")

DataFrame sorted by 'date'.
Data split chronologically into training (70%) and testing (30%).
Training set shape: (3612, 6183)
Testing set shape: (1549, 6183)

First 5 rows of Training Data:

,date,time_09:03:28.617601,time_09:03:29.105569,time_09:03:29.967462,time_09:03:30.84641,time_09:03:31.676519,time_09:03:31.974608,time_09:03:32.2486,time_09:03:33.483746,time_09:03:34.977824,...,message_3.34286,message_ABSENT,message_CLOSE,message_END,message_OFF,message_ON,message_OPEN,message_PRESENT,message_START,message_STOP_INSTRUCT
613,2008-03-28,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
456,2008-03-28,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
457,2008-03-28,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
458,2008-03-28,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
459,2008-03-28,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False

First 5 rows of Test Data:

,date,time_09:03:28.617601,time_09:03:29.105569,time_09:03:29.967462,time_09:03:30.84641,time_09:03:31.676519,time_09:03:31.974608,time_09:03:32.2486,time_09:03:33.483746,time_09:03:34.977824,...,message_3.34286,message_ABSENT,message_CLOSE,message_END,message_OFF,message_ON,message_OPEN,message_PRESENT,message_START,message_STOP_INSTRUCT
4662,2008-06-04,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4661,2008-06-04,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
4660,2008-06-04,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4659,2008-06-04,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4658,2008-06-04,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

### 9. Export Train and Test Data as NumPy Files

This step saves the `df_train` and `df_test` DataFrames as `.npy` files, which are convenient for storing NumPy arrays.

In [ ]:
import numpy as np

if 'df_train' in locals() and 'df_test' in locals():
    # Convert DataFrames to NumPy arrays
    # You might want to decide which columns to export if not all are needed.
    # For simplicity, here we convert the entire DataFrame.
    # If you have non-numeric data that can't be converted, you'll need to handle it.

    # Note: .values converts the DataFrame to a NumPy array. If your DataFrame contains
    # object dtypes (e.g., original 'date' column before conversion or if any one-hot encoded
    # columns were left as boolean), numpy might cast them to object dtype arrays.
    # Ensure your data is numeric before saving if you expect a numeric array.

    # Convert 'date' column to numerical representation (e.g., Unix timestamp) if it needs to be included
    # and is still a datetime object. Otherwise, drop it before converting to array if it's not a feature.
    # For this example, let's assume we want to save all processed numerical features.

    # Make a copy to avoid modifying the original df_train/df_test during this conversion step
    df_train_export = df_train.copy()
    df_test_export = df_test.copy()

    # Drop the original 'date' column if it's still present and not needed as a feature in the npy file
    if 'date' in df_train_export.columns:
        df_train_export = df_train_export.drop(columns=['date'])
    if 'date' in df_test_export.columns:
        df_test_export = df_test_export.drop(columns=['date'])

    train_array = df_train_export.to_numpy()
    test_array = df_test_export.to_numpy()

    # Define paths to save the .npy files
    train_output_path = '/content/drive/MyDrive/Datasets/CASAS-Cleaned/CASAS_train.npy'
    test_output_path = '/content/drive/MyDrive/Datasets/CASAS-Cleaned/CASAS_test.npy'

    np.save(train_output_path, train_array)
    np.save(test_output_path, test_array)

    print(f"Training data saved to: {train_output_path}")
    print(f"Testing data saved to: {test_output_path}")

    # You can verify by loading them back
    # loaded_train = np.load(train_output_path)
    # loaded_test = np.load(test_output_path)
    # print(f"\nLoaded train array shape: {loaded_train.shape}")
    # print(f"Loaded test array shape: {loaded_test.shape}")
else:
    print("Training and testing DataFrames not found. Please ensure the previous step ran successfully.")

Training data saved to: /content/drive/MyDrive/Datasets/CASAS-Cleaned/CASAS_train.npy
Testing data saved to: /content/drive/MyDrive/Datasets/CASAS-Cleaned/CASAS_test.npy