<a href="https://colab.research.google.com/github/melkanzi/PhD/blob/main/N_BaIoT_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data Preprocessing Pipeline for N-BaIoT Dataset

This notebook will guide you through the preprocessing steps for the N-BaIoT dataset, which is assumed to be in a zip file on your Google Drive.

### Step 1: Mount Google Drive and Unzip the Dataset

First, we need to mount Google Drive to access your files. After mounting, please update the `zip_file_path` variable with the correct path to your N-BaIoT zip file on Drive.

In [ ]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Define the path to your zip file on Google Drive
# IMPORTANT: Update this path to your specific file location
zip_file_path = '/content/drive/MyDrive/Datasets/N-BaIoT.zip' # Example path, please adjust!

# Define the directory where you want to extract the files
extraction_path = './N-BaIoT_extracted'

import os
import zipfile

# Create the extraction directory if it doesn't exist
os.makedirs(extraction_path, exist_ok=True)

# Unzip the file
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extraction_path)

print(f"Dataset unzipped to: {extraction_path}")

# List the contents of the extracted folder to identify the data files
print("Contents of extracted folder:")
for root, dirs, files in os.walk(extraction_path):
    for name in files:
        print(os.path.join(root, name))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

KeyboardInterrupt:

### Step 2: Load the Dataset

Assuming the unzipped dataset contains CSV files, we will load them into a Pandas DataFrame. You might need to adjust the `data_file_path` to point to the actual data file within the extracted directory.

In [ ]:
import pandas as pd
import os

all_dfs = []

# Iterate through each item in the extraction path
for item_name in os.listdir(extraction_path):
    item_path = os.path.join(extraction_path, item_name)

    # Check if it's a directory (assumed to be a device folder)
    if os.path.isdir(item_path):
        benign_file_path = os.path.join(item_path, 'benign_traffic.csv')

        if os.path.exists(benign_file_path):
            try:
                temp_df = pd.read_csv(benign_file_path)
                # Add columns to identify the device and traffic type
                temp_df['device_category'] = item_name  # Device name from folder name
                temp_df['traffic_type'] = 'benign' # This file contains benign traffic
                all_dfs.append(temp_df)
                print(f"Loaded {benign_file_path} with shape {temp_df.shape}")
            except Exception as e:
                print(f"Error loading {benign_file_path}: {e}")

if all_dfs:
    df = pd.concat(all_dfs, ignore_index=True)
    print("\nAll benign traffic datasets loaded and concatenated successfully.")
    print(f"Final shape of the dataset: {df.shape}")
    display(df.head())
else:
    print("No 'benign_traffic.csv' files were found or loaded in the subdirectories.")
    df = pd.DataFrame() # Initialize an empty DataFrame if nothing was loaded

Loaded ./N-BaIoT_extracted/Samsung_SNH_1011_N_Webcam/benign_traffic.csv with shape (52150, 117)
Loaded ./N-BaIoT_extracted/Provision_PT_737E_Security_Camera/benign_traffic.csv with shape (62154, 117)
Loaded ./N-BaIoT_extracted/Danmini_Doorbell/benign_traffic.csv with shape (49548, 117)
Loaded ./N-BaIoT_extracted/SimpleHome_XCS7_1003_WHT_Security_Camera/benign_traffic.csv with shape (19528, 117)
Loaded ./N-BaIoT_extracted/Philips_B120N10_Baby_Monitor/benign_traffic.csv with shape (124430, 117)
Loaded ./N-BaIoT_extracted/Ennio_Doorbell/benign_traffic.csv with shape (39100, 117)
Loaded ./N-BaIoT_extracted/Ecobee_Thermostat/benign_traffic.csv with shape (13113, 117)
Loaded ./N-BaIoT_extracted/SimpleHome_XCS7_1002_WHT_Security_Camera/benign_traffic.csv with shape (46585, 117)
Loaded ./N-BaIoT_extracted/Provision_PT_838_Security_Camera/benign_traffic.csv with shape (98514, 117)

All benign traffic datasets loaded and concatenated successfully.
Final shape of the dataset: (505122, 117)

,MI_dir_L5_weight,MI_dir_L5_mean,MI_dir_L5_variance,MI_dir_L3_weight,MI_dir_L3_mean,MI_dir_L3_variance,MI_dir_L1_weight,MI_dir_L1_mean,MI_dir_L1_variance,MI_dir_L0.1_weight,...,HpHp_L0.1_pcc,HpHp_L0.01_weight,HpHp_L0.01_mean,HpHp_L0.01_std,HpHp_L0.01_magnitude,HpHp_L0.01_radius,HpHp_L0.01_covariance,HpHp_L0.01_pcc,device_category,traffic_type
0,1.000000,60.000000,0.000000,1.000000,60.000000,0.000000,1.000000,60.000000,0.000000,1.000000,...,0.0,1.000000,60.000000,0.000000,60.000000,0.000000,0.0,0.0,Samsung_SNH_1011_N_Webcam,benign
1,1.000000,70.000000,0.000000,1.000000,70.000000,0.000000,1.000000,70.000000,0.000000,1.000000,...,0.0,1.000000,70.000000,0.000000,70.000000,0.000000,0.0,0.0,Samsung_SNH_1011_N_Webcam,benign
2,1.000008,89.999836,0.003289,1.000889,89.982231,0.355061,1.096162,88.245473,32.012169,1.791226,...,0.0,1.000000,90.000000,0.000000,90.000000,0.000000,0.0,0.0,Samsung_SNH_1011_N_Webcam,benign
3,1.000000,322.000000,0.000000,1.000000,322.000000,0.000000,1.000000,322.000000,0.000000,1.000000,...,0.0,11.163562,380.087760,92.127549,380.087760,8487.485312,0.0,0.0,Samsung_SNH_1011_N_Webcam,benign
4,1.784845,328.723273,35.476876,1.864710,328.435318,35.810498,1.952701,328.145333,35.978878,1.995166,...,0.0,12.158154,376.297073,89.161260,376.297073,7949.730316,0.0,0.0,Samsung_SNH_1011_N_Webcam,benign

### Step 3: Handle Missing Values

We will remove rows with any missing values from the dataset. This is a simple approach; more sophisticated methods (like imputation) could be used if necessary.

In [ ]:
print(f"Original shape: {df.shape}")
missing_values_count = df.isnull().sum().sum()

if missing_values_count > 0:
    df_cleaned_missing = df.dropna()
    print(f"Removed {df.shape[0] - df_cleaned_missing.shape[0]} rows with missing values.")
    print(f"New shape after handling missing values: {df_cleaned_missing.shape}")
    df = df_cleaned_missing
else:
    print("No missing values found.")

display(df.head())

Original shape: (505122, 117)
Removed 1 rows with missing values.
New shape after handling missing values: (505121, 117)

,MI_dir_L5_weight,MI_dir_L5_mean,MI_dir_L5_variance,MI_dir_L3_weight,MI_dir_L3_mean,MI_dir_L3_variance,MI_dir_L1_weight,MI_dir_L1_mean,MI_dir_L1_variance,MI_dir_L0.1_weight,...,HpHp_L0.1_pcc,HpHp_L0.01_weight,HpHp_L0.01_mean,HpHp_L0.01_std,HpHp_L0.01_magnitude,HpHp_L0.01_radius,HpHp_L0.01_covariance,HpHp_L0.01_pcc,device_category,traffic_type
0,1.000000,60.000000,0.000000,1.000000,60.000000,0.000000,1.000000,60.000000,0.000000,1.000000,...,0.0,1.000000,60.000000,0.000000,60.000000,0.000000,0.0,0.0,Samsung_SNH_1011_N_Webcam,benign
1,1.000000,70.000000,0.000000,1.000000,70.000000,0.000000,1.000000,70.000000,0.000000,1.000000,...,0.0,1.000000,70.000000,0.000000,70.000000,0.000000,0.0,0.0,Samsung_SNH_1011_N_Webcam,benign
2,1.000008,89.999836,0.003289,1.000889,89.982231,0.355061,1.096162,88.245473,32.012169,1.791226,...,0.0,1.000000,90.000000,0.000000,90.000000,0.000000,0.0,0.0,Samsung_SNH_1011_N_Webcam,benign
3,1.000000,322.000000,0.000000,1.000000,322.000000,0.000000,1.000000,322.000000,0.000000,1.000000,...,0.0,11.163562,380.087760,92.127549,380.087760,8487.485312,0.0,0.0,Samsung_SNH_1011_N_Webcam,benign
4,1.784845,328.723273,35.476876,1.864710,328.435318,35.810498,1.952701,328.145333,35.978878,1.995166,...,0.0,12.158154,376.297073,89.161260,376.297073,7949.730316,0.0,0.0,Samsung_SNH_1011_N_Webcam,benign

### Step 4: Remove Duplicate Rows

Identify and remove any exact duplicate rows in the dataset.

In [ ]:
print(f"Shape before removing duplicates: {df.shape}")
duplicates_count = df.duplicated().sum()

if duplicates_count > 0:
    df_no_duplicates = df.drop_duplicates()
    print(f"Removed {duplicates_count} duplicate rows.")
    print(f"Shape after removing duplicates: {df_no_duplicates.shape}")
    df = df_no_duplicates
else:
    print("No duplicate rows found.")

display(df.head())

Shape before removing duplicates: (505121, 117)
Removed 37399 duplicate rows.
Shape after removing duplicates: (467722, 117)

,MI_dir_L5_weight,MI_dir_L5_mean,MI_dir_L5_variance,MI_dir_L3_weight,MI_dir_L3_mean,MI_dir_L3_variance,MI_dir_L1_weight,MI_dir_L1_mean,MI_dir_L1_variance,MI_dir_L0.1_weight,...,HpHp_L0.1_pcc,HpHp_L0.01_weight,HpHp_L0.01_mean,HpHp_L0.01_std,HpHp_L0.01_magnitude,HpHp_L0.01_radius,HpHp_L0.01_covariance,HpHp_L0.01_pcc,device_category,traffic_type
0,1.000000,60.000000,0.000000,1.000000,60.000000,0.000000,1.000000,60.000000,0.000000,1.000000,...,0.0,1.000000,60.000000,0.000000,60.000000,0.000000,0.0,0.0,Samsung_SNH_1011_N_Webcam,benign
1,1.000000,70.000000,0.000000,1.000000,70.000000,0.000000,1.000000,70.000000,0.000000,1.000000,...,0.0,1.000000,70.000000,0.000000,70.000000,0.000000,0.0,0.0,Samsung_SNH_1011_N_Webcam,benign
2,1.000008,89.999836,0.003289,1.000889,89.982231,0.355061,1.096162,88.245473,32.012169,1.791226,...,0.0,1.000000,90.000000,0.000000,90.000000,0.000000,0.0,0.0,Samsung_SNH_1011_N_Webcam,benign
3,1.000000,322.000000,0.000000,1.000000,322.000000,0.000000,1.000000,322.000000,0.000000,1.000000,...,0.0,11.163562,380.087760,92.127549,380.087760,8487.485312,0.0,0.0,Samsung_SNH_1011_N_Webcam,benign
4,1.784845,328.723273,35.476876,1.864710,328.435318,35.810498,1.952701,328.145333,35.978878,1.995166,...,0.0,12.158154,376.297073,89.161260,376.297073,7949.730316,0.0,0.0,Samsung_SNH_1011_N_Webcam,benign

### Step 5: Fix Inconsistent Formats (Initial Check)

This step typically involves inspecting column data types and unique values to identify inconsistencies. Without specific knowledge of the N-BaIoT dataset's columns, we'll perform a general check and conversion for common types. You might need to customize this based on your data.

We'll ensure numeric columns are indeed numeric and handle potential errors during conversion.

In [ ]:
print("Data types before format fixing:")
print(df.info())

# Columns identified as categorical labels that should NOT be converted to numeric
# These will be handled by One-Hot Encoding later.
categorical_label_cols = ['device_category', 'traffic_type']

# Attempt to convert all columns that should be numeric to numeric, coercing errors
for col in df.columns:
    if col in categorical_label_cols:
        print(f"Skipping numerical conversion for identified categorical label column: '{col}'")
        continue # Skip to the next column

    if df[col].dtype == 'object':
        try:
            # Try converting to numeric, if it fails, keep as object or convert to category
            original_col_data = df[col].copy() # Keep a copy to compare after conversion
            df[col] = pd.to_numeric(df[col], errors='coerce')

            # If conversion was successful, check for new NaNs introduced by coercion
            # These new NaNs mean there were non-numeric strings in a column expected to be numeric.
            newly_nan_rows = df[df[col].isnull() & original_col_data.notnull()].shape[0]
            if newly_nan_rows > 0:
                initial_rows = df.shape[0]
                df.dropna(subset=[col], inplace=True)
                print(f"Removed {initial_rows - df.shape[0]} rows due to non-numeric values in '{col}' after attempted conversion.")
        except Exception:
            # If conversion fails for other reasons, it's likely a true string/categorical column
            # but not in our explicit skip list, so we might want to inspect it.
            print(f"Warning: Could not convert column '{col}' to numeric, keeping as original type.")

print("\nData types after initial format fixing:")
print(df.info())
display(df.head())

Data types before format fixing:
<class 'pandas.core.frame.DataFrame'>
Index: 467722 entries, 0 to 502802
Columns: 117 entries, MI_dir_L5_weight to traffic_type
dtypes: float64(115), object(2)
memory usage: 421.1+ MB
None
Skipping numerical conversion for identified categorical label column: 'device_category'
Skipping numerical conversion for identified categorical label column: 'traffic_type'

Data types after initial format fixing:
<class 'pandas.core.frame.DataFrame'>
Index: 467722 entries, 0 to 502802
Columns: 117 entries, MI_dir_L5_weight to traffic_type
dtypes: float64(115), object(2)
memory usage: 421.1+ MB
None

,MI_dir_L5_weight,MI_dir_L5_mean,MI_dir_L5_variance,MI_dir_L3_weight,MI_dir_L3_mean,MI_dir_L3_variance,MI_dir_L1_weight,MI_dir_L1_mean,MI_dir_L1_variance,MI_dir_L0.1_weight,...,HpHp_L0.1_pcc,HpHp_L0.01_weight,HpHp_L0.01_mean,HpHp_L0.01_std,HpHp_L0.01_magnitude,HpHp_L0.01_radius,HpHp_L0.01_covariance,HpHp_L0.01_pcc,device_category,traffic_type
0,1.000000,60.000000,0.000000,1.000000,60.000000,0.000000,1.000000,60.000000,0.000000,1.000000,...,0.0,1.000000,60.000000,0.000000,60.000000,0.000000,0.0,0.0,Samsung_SNH_1011_N_Webcam,benign
1,1.000000,70.000000,0.000000,1.000000,70.000000,0.000000,1.000000,70.000000,0.000000,1.000000,...,0.0,1.000000,70.000000,0.000000,70.000000,0.000000,0.0,0.0,Samsung_SNH_1011_N_Webcam,benign
2,1.000008,89.999836,0.003289,1.000889,89.982231,0.355061,1.096162,88.245473,32.012169,1.791226,...,0.0,1.000000,90.000000,0.000000,90.000000,0.000000,0.0,0.0,Samsung_SNH_1011_N_Webcam,benign
3,1.000000,322.000000,0.000000,1.000000,322.000000,0.000000,1.000000,322.000000,0.000000,1.000000,...,0.0,11.163562,380.087760,92.127549,380.087760,8487.485312,0.0,0.0,Samsung_SNH_1011_N_Webcam,benign
4,1.784845,328.723273,35.476876,1.864710,328.435318,35.810498,1.952701,328.145333,35.978878,1.995166,...,0.0,12.158154,376.297073,89.161260,376.297073,7949.730316,0.0,0.0,Samsung_SNH_1011_N_Webcam,benign

### Step 6: Convert Text Labels to Numeric Form (One-Hot Encoding)

Assuming there is a 'device_category' column that contains text labels, we will apply One-Hot Encoding to convert it into a numeric format. If your categorical column has a different name, please adjust `categorical_column`.

In [ ]:
from sklearn.preprocessing import OneHotEncoder

# IMPORTANT: Identify your categorical column for device categories
# For N-BaIoT, this might be 'device_category', 'type', or a similar label column.
# Inspect df.columns and df['your_label_column'].unique() if unsure.

categorical_column = 'device_category' # Placeholder, adjust to your actual column name

if categorical_column in df.columns and df[categorical_column].dtype == 'object':
    print(f"Applying One-Hot Encoding to '{categorical_column}'...")
    encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
    encoded_features = encoder.fit_transform(df[[categorical_column]])

    # Create a DataFrame from the encoded features
    encoded_df = pd.DataFrame(encoded_features, columns=encoder.get_feature_names_out([categorical_column]), index=df.index)

    # Drop the original categorical column and concatenate the new encoded columns
    df = pd.concat([df.drop(columns=[categorical_column]), encoded_df], axis=1)
    print("One-Hot Encoding applied.")
    print(f"Shape after One-Hot Encoding: {df.shape}")
else:
    print(f"Categorical column '{categorical_column}' not found or is not of object dtype. Skipping One-Hot Encoding.")

display(df.head())

Applying One-Hot Encoding to 'device_category'...
One-Hot Encoding applied.
Shape after One-Hot Encoding: (467722, 125)

,MI_dir_L5_weight,MI_dir_L5_mean,MI_dir_L5_variance,MI_dir_L3_weight,MI_dir_L3_mean,MI_dir_L3_variance,MI_dir_L1_weight,MI_dir_L1_mean,MI_dir_L1_variance,MI_dir_L0.1_weight,...,traffic_type,device_category_Danmini_Doorbell,device_category_Ecobee_Thermostat,device_category_Ennio_Doorbell,device_category_Philips_B120N10_Baby_Monitor,device_category_Provision_PT_737E_Security_Camera,device_category_Provision_PT_838_Security_Camera,device_category_Samsung_SNH_1011_N_Webcam,device_category_SimpleHome_XCS7_1002_WHT_Security_Camera,device_category_SimpleHome_XCS7_1003_WHT_Security_Camera
0,1.000000,60.000000,0.000000,1.000000,60.000000,0.000000,1.000000,60.000000,0.000000,1.000000,...,benign,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,1.000000,70.000000,0.000000,1.000000,70.000000,0.000000,1.000000,70.000000,0.000000,1.000000,...,benign,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,1.000008,89.999836,0.003289,1.000889,89.982231,0.355061,1.096162,88.245473,32.012169,1.791226,...,benign,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,1.000000,322.000000,0.000000,1.000000,322.000000,0.000000,1.000000,322.000000,0.000000,1.000000,...,benign,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1.784845,328.723273,35.476876,1.864710,328.435318,35.810498,1.952701,328.145333,35.978878,1.995166,...,benign,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

### Step 7: Apply Normalization (Min-Max Scaling)

We will apply Min-Max scaling to all numerical features to bring them into a range of [0, 1]. This helps in improving the performance of many machine learning algorithms.

In [ ]:
from sklearn.preprocessing import MinMaxScaler

print("Applying Min-Max Normalization...")

# Identify numerical columns for scaling
# Exclude any one-hot encoded columns if you want to scale only original numerical features
# For simplicity, we'll scale all numerical columns here.
numerical_cols = df.select_dtypes(include=['number']).columns

if len(numerical_cols) > 0:
    scaler = MinMaxScaler()
    df[numerical_cols] = scaler.fit_transform(df[numerical_cols])
    print("Min-Max Normalization applied to numerical columns.")
else:
    print("No numerical columns found to apply Min-Max Normalization.")

display(df.head())

Applying Min-Max Normalization...
Min-Max Normalization applied to numerical columns.

,MI_dir_L5_weight,MI_dir_L5_mean,MI_dir_L5_variance,MI_dir_L3_weight,MI_dir_L3_mean,MI_dir_L3_variance,MI_dir_L1_weight,MI_dir_L1_mean,MI_dir_L1_variance,MI_dir_L0.1_weight,...,traffic_type,device_category_Danmini_Doorbell,device_category_Ecobee_Thermostat,device_category_Ennio_Doorbell,device_category_Philips_B120N10_Baby_Monitor,device_category_Provision_PT_737E_Security_Camera,device_category_Provision_PT_838_Security_Camera,device_category_Samsung_SNH_1011_N_Webcam,device_category_SimpleHome_XCS7_1002_WHT_Security_Camera,device_category_SimpleHome_XCS7_1003_WHT_Security_Camera
0,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,benign,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.000000e+00,0.007180,0.000000e+00,0.000000,0.007190,0.000000e+00,0.000000,0.007278,0.000000,0.000000,...,benign,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,3.528337e-08,0.021541,6.687801e-09,0.000003,0.021559,7.412823e-07,0.000215,0.020556,0.000067,0.001125,...,benign,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.000000e+00,0.188124,0.000000e+00,0.000000,0.188390,0.000000e+00,0.000000,0.190676,0.000000,0.000000,...,benign,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,3.367624e-03,0.192952,7.213595e-05,0.003017,0.193018,7.476383e-05,0.002130,0.195149,0.000075,0.001415,...,benign,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

### Step 8: Split the Data (Stratified Random Split)

We will perform a 70%-30% stratified random split based on the 'device_category' (or the one-hot encoded representation of it) to ensure that each device type is adequately represented in both the training and test sets. You will need to specify your target column for stratification.

In [ ]:
from sklearn.model_selection import train_test_split
import numpy as np

# Identify columns related to device categories after One-Hot Encoding
target_categorical_prefix = 'device_category_'
ohe_device_category_cols = [col for col in df.columns if col.startswith(target_categorical_prefix)]

# Also identify 'traffic_type' if it's present and should be treated as a label/excluded from features
# Assuming 'traffic_type' is a label and not a feature for the main classification task.
other_label_cols = ['traffic_type']

if not ohe_device_category_cols:
    print("Error: No One-Hot Encoded device category columns found. Cannot perform stratified split.")
    print("Please ensure 'device_category' was correctly one-hot encoded in the previous step.")
    X_train, X_test, y_train, y_test = None, None, None, None
else:
    # Reconstruct a single categorical series for stratification purposes
    # This assumes that for each row, exactly one of the ohe_device_category_cols is 1.
    y_stratify = df[ohe_device_category_cols].idxmax(axis=1)

    # Define features (X) by dropping all label-related columns
    features_to_drop = ohe_device_category_cols + other_label_cols
    X = df.drop(columns=features_to_drop, errors='ignore')

    # Define the actual labels (y) as the one-hot encoded device categories
    y = df[ohe_device_category_cols]

    # Perform the stratified split using y_stratify for stratification
    X_train, X_test, y_train_ohe, y_test_ohe, y_stratify_train, y_stratify_test = train_test_split(
        X, y, y_stratify, test_size=0.3, random_state=42, stratify=y_stratify
    )

    # For the final export, y_train and y_test should be the one-hot encoded labels
    y_train = y_train_ohe
    y_test = y_test_ohe

    print("Data split into training and testing sets (70%-30% stratified).")
    print(f"X_train shape: {X_train.shape}")
    print(f"X_test shape: {X_test.shape}")
    print(f"y_train (OHE labels) shape: {y_train.shape}")
    print(f"y_test (OHE labels) shape: {y_test.shape}")

    # You can also check the distribution of classes in train and test sets using the stratification target
    print("\nClass distribution in original dataset (stratification target):")
    print(y_stratify.value_counts(normalize=True))
    print("\nClass distribution in training set (stratification target):")
    print(y_stratify_train.value_counts(normalize=True))
    print("\nClass distribution in test set (stratification target):")
    print(y_stratify_test.value_counts(normalize=True))

    # train_set and test_set variables are not strictly needed for the final .npy export
    # but if needed, they would be constructed like this:
    # train_set = pd.concat([X_train, y_train], axis=1)
    # test_set = pd.concat([X_test, y_test], axis=1)

Data split into training and testing sets (70%-30% stratified).
X_train shape: (327405, 115)
X_test shape: (140317, 115)
y_train (OHE labels) shape: (327405, 9)
y_test (OHE labels) shape: (140317, 9)

Class distribution in original dataset (stratification target):
device_category_Philips_B120N10_Baby_Monitor                0.255201
device_category_Provision_PT_838_Security_Camera            0.200963
device_category_Provision_PT_737E_Security_Camera           0.117953
device_category_Samsung_SNH_1011_N_Webcam                   0.105958
device_category_SimpleHome_XCS7_1002_WHT_Security_Camera    0.091473
device_category_Danmini_Doorbell                            0.086365
device_category_Ennio_Doorbell                              0.075707
device_category_SimpleHome_XCS7_1003_WHT_Security_Camera    0.038348
device_category_Ecobee_Thermostat                           0.028032
Name: proportion, dtype: float64

Class distribution in training set (stratification target):
device_category_Philips_B120N10_Baby_Monitor                0.255201
device_category_Provision_PT_838_Security_Camera            0.200962
device_category_Provision_PT_737E_Security_Camera           0.117952
device_category_Samsung_SNH_1011_N_Webcam                   0.105957
device_category_SimpleHome_XCS7_1002_WHT_Security_Camera    0.091474
device_category_Danmini_Doorbell                            0.086367
device_category_Ennio_Doorbell                              0.075707
device_category_SimpleHome_XCS7_1003_WHT_Security_Camera    0.038347
device_category_Ecobee_Thermostat                           0.028033
Name: proportion, dtype: float64

Class distribution in test set (stratification target):
device_category_Philips_B120N10_Baby_Monitor                0.255201
device_category_Provision_PT_838_Security_Camera            0.200966
device_category_Provision_PT_737E_Security_Camera           0.117954
device_category_Samsung_SNH_1011_N_Webcam                   0.105960
device_category_SimpleHome_XCS7_1002_WHT_Security_Camera    0.091471
device_category_Danmini_Doorbell                            0.086362
device_category_Ennio_Doorbell                              0.075707
device_category_SimpleHome_XCS7_1003_WHT_Security_Camera    0.038349
device_category_Ecobee_Thermostat                           0.028029
Name: proportion, dtype: float64

### Step 9: Export Training and Test Sets as .npy Files

Finally, we will save the preprocessed training and test sets as NumPy `.npy` files for later use.

In [ ]:
if X_train is not None and X_test is not None and y_train is not None and y_test is not None:
    output_dir = './preprocessed_N-BaIoT'
    os.makedirs(output_dir, exist_ok=True)

    # Save features and labels separately for flexibility
    np.save(os.path.join(output_dir, 'X_train.npy'), X_train.to_numpy())
    np.save(os.path.join(output_dir, 'X_test.npy'), X_test.to_numpy())
    np.save(os.path.join(output_dir, 'y_train.npy'), y_train.to_numpy())
    np.save(os.path.join(output_dir, 'y_test.npy'), y_test.to_numpy())

    print(f"Preprocessed data saved to '{output_dir}' as .npy files:")
    print("  X_train.npy")
    print("  X_test.npy")
    print("  y_train.npy")
    print("  y_test.npy")

else:
    print("Skipping .npy export as data splitting was not successful.")

Preprocessed data saved to './preprocessed_N-BaIoT' as .npy files:
  X_train.npy
  X_test.npy
  y_train.npy
  y_test.npy